# Generated by Django 3.1 on 2020-09-12 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200912_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 12, 12, 38, 44, 249655)),
        ),
    ]
